version: '3'

services:
    influx:
        image: "influxdb"
        ports:
            - 8086:8086
            - 2003:2003
        volumes:
            - /var/lib/influxdb
            - ./JMeter_Docker/influx-database/influxdb.conf:/etc/influxdb/influxdb.conf
        environment:   
            - INFLUXDB_GRAPHITE_ENABLED=true
            - INFLUXDB_DB="jmeter"
    grafana:
        image: "grafana/grafana"
        ports: 
            - 3005:3005
        volumes:
            - /var/lib/grafana
        environment:
            - GF_SERVER_HTTP_HOST= 127.0.0.1
            - GF_SERVER_HTTP_PORT=3005
    
    jmmaster:
        image: "sukram42/jmmaster"
        volumes:
         - ./JMeter_Docker/tests/steptest.jmx:/etc/tests/steptest.jmx
         - ./JMeter_Docker/plugins/jmeter-plugins-casutg-2.1.jar:/jmeter/apache-jmeter-3.3/lib/jmeter-plugins-casutg-2.1.jar
        tty: true
        network_mode: "host"
    
    jmserver:
        image: "sukram42/jmserver" 
        volumes:
            - ./JMeter_Docker/plugins/jmeter-plugins-casutg-2.1.jar:/jmeter/apache-jmeter-3.3/lib/jmeter-plugins-casutg-2.1.jar
        network_mode: "host"