version: '3'

services:
    influx:
        image: "influxdb"
        ports:
            - 8086:8086
            - 2003:2003
        volumes:
            - /var/lib/influxdb
            - ./JMeter_Docker/influx-database/influxdb.conf:/etc/influxdb/influxdb.conf
        environment:   
            - INFLUXDB_GRAPHITE_ENABLED=true
            - INFLUXDB_DB='jmeter'
    grafana:
        image: "grafana/grafana"
        ports: 
            - 3005:3005
        volumes:
            - /var/lib/grafana
        environment:
            - GF_SERVER_HTTP_HOST= 127.0.0.1
            - GF_SERVER_HTTP_PORT=3005
            
    jmeterclient:
        image: "sukram42/jmserver"