version: '3.3'

services:
    webapp:
        image: "tw-ucp2.twlon.com/admin/scale_webapp"
        ports:
            - 3000:3000
        environment:
            - DATABASE_HOST=10.3.16.146
        networks:
            - demo
    datamining:
        image: "tw-ucp2.twlon.com/admin/scale_datamining:latest"
        environment:
            - NODE_ENV=production
        networks:
            - demo
    influx:
        image: "influxdb"
        ports:
            - 8086:8086
            - 2003:2003
        volumes:
            - influxdata:/var/lib/influxdb
        configs:
            - source: influxconf
              target: /etc/influxdb/influxdb.conf
        environment:   
            - INFLUXDB_GRAPHITE_ENABLED=true
            - INFLUXDB_DB="jmeter"
        networks:
            - demo
    
    grafana:
        image: "grafana/grafana"
        ports:
            - 3005:3005
        volumes:
            - grafanadata:/var/lib/grafana
        networks:
             - demo
        environment:
            - GF_SERVER_HTTP_HOST=127.0.0.1
            - GF_SERVER_HTTP_PORT=3005
            - INFLUX=influx:8086

    jmserver:
        image: "tw-ucp2.twlon.com/admin/scale_jmserver"
        configs:
            - source: jmserver
              target: /jmeter/apache-jmeter-3.3/lib/jmeter-plugins-casutg-2.1.jar
        networks:
            - demo
            
    jmmaster:
        image: "tw-ucp2.twlon.com/admin/scale_jmmaster"
        ports:
            - "3007:3007"
        volumes:
            - jmmaster:/etc/tests
        configs:
            - source: jmserver
              target: /jmeter/apache-jmeter-3.3/lib/jmeter-plugins-casutg-2.1.jar
        tty: true
        networks:
             - demo

networks:
    demo:

configs:
    influxconf:
        file: ./JMeter_Docker/influx-database/influxdb.conf
            
    jmserver:
        file: ./JMeter_Docker/plugins/jmeter-plugins-casutg-2.1.jar

volumes:
    influxdata:
    grafanadata:
    jmmaster: